"""Install a Jupyter kernelspec that starts the kernel through `pixi run`.

Needed because VSCode (and plain Jupyter) discover `.pixi/envs/explore/bin/
python` and exec `ipykernel_launcher` themselves, which skips pixi activation.
The kernel then misses whatever activation sets up -- most importantly, for
this package, `FDB5_DIR` and `LD_LIBRARY_PATH`, without which `findlibs` cannot
locate `libfdb5.so` and every `open_run` fails at import time.

Setting those from inside the notebook does not help: `LD_LIBRARY_PATH` is read
by the dynamic loader when the process starts, so it has to be in place before
the kernel execs.

So this writes two files into the kernel directory:

    launch.sh     module loads + FDB env + exec pixi run ... ipykernel_launcher
    kernel.json   argv pointing at launch.sh

Run once per machine, from a shell where FDB5_DIR is already exported:

    pixi run -e explore kernel
    pixi run -e explore kernel --fdb5-dir /path/to/climateDT/build_intel
    pixi run -e explore kernel --module intel        # if libfdb5 needs the toolchain

Then pick "destine-fdb (pixi)" as the notebook kernel in VSCode.
"""

import argparse
import json
import os
import shutil
import stat
import sys
from pathlib import Path


DEFAULT_NAME = "destine-fdb"
DEFAULT_DISPLAY_NAME = "destine-fdb (pixi)"
DEFAULT_ENVIRONMENT = "explore"


def parse_args():
    p = argparse.ArgumentParser(
        description="Install a pixi-activating Jupyter kernelspec for this project.",
    )
    p.add_argument("--name", default=DEFAULT_NAME, help="kernelspec directory name")
    p.add_argument("--display-name", default=DEFAULT_DISPLAY_NAME)
    p.add_argument("--environment", default=DEFAULT_ENVIRONMENT,
                   help="pixi environment the kernel runs in")
    p.add_argument("--manifest-path", default=None,
                   help="pixi.toml to run against (default: this repo's)")
    p.add_argument("--pixi", default=None, help="path to the pixi executable")
    p.add_argument("--prefix", default=None,
                   help="kernelspec root (default: ~/.local/share/jupyter)")
    p.add_argument("--module", action="append", default=[], dest="modules",
                   help="environment module to load before the kernel starts "
                        "(repeatable)")
    p.add_argument("--fdb5-dir", default=None,
                   help="model build dir holding lib/libfdb5.so "
                        "(default: $FDB5_DIR from the current shell)")
    p.add_argument("--no-fdb-env", action="store_true",
                   help="write a plain kernel with no FDB variables")
    p.add_argument("--dry-run", action="store_true")
    return p.parse_args()


def find_pixi(explicit):
    """Locate pixi. It is on PATH under `pixi run`, but not in every shell."""
    # Deliberately not resolve(): on a Homebrew laptop that would bake in
    # .../Cellar/pixi/<version>/bin/pixi, which dies at the next upgrade.
    if explicit:
        return os.path.abspath(os.path.expanduser(explicit))
    found = shutil.which("pixi")
    if found:
        return os.path.abspath(found)
    fallback = Path.home() / ".pixi" / "bin" / "pixi"
    if fallback.exists():
        return str(fallback)
    sys.exit("pixi executable not found; pass --pixi /path/to/pixi")


def resolve_fdb5_dir(args):
    """The build dir to hardcode into the launcher, or None if not wanted."""
    if args.no_fdb_env:
        return None
    chosen = args.fdb5_dir or os.environ.get("FDB5_DIR")
    if not chosen:
        sys.exit("FDB5_DIR is not set and --fdb5-dir was not given.\n"
                 "Either export it and re-run, pass --fdb5-dir /path/to/build_intel,\n"
                 "or pass --no-fdb-env for a kernel that only reads zarr/netCDF.")
    chosen = os.path.expanduser(chosen)
    library = Path(chosen) / "lib" / "libfdb5.so"
    if not library.exists():
        print(f"warning: {library} does not exist -- pyfdb will not find libfdb5",
              file=sys.stderr)
    return chosen


def render_launcher(args, pixi, manifest, fdb5_dir):
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by tools/make_kernel.py -- edits are lost on the next run.",
        "set -euo pipefail",
        "",
    ]

    if args.modules:
        # `module` is a shell function; a kernel process gets no login shell,
        # so the init script has to be sourced explicitly.
        lines += [
            'if ! command -v module >/dev/null 2>&1; then',
            "    for init in /etc/profile.d/modules.sh /etc/profile.d/lmod.sh \\",
            "                /usr/share/lmod/lmod/init/bash; do",
            '        if [ -r "$init" ]; then . "$init"; break; fi',
            "    done",
            "fi",
        ]
        lines += [f"module load {m}" for m in args.modules]
        lines.append("")

    if fdb5_dir:
        lines += [
            f'export FDB5_DIR="{fdb5_dir}"',
            # Prepend, never replace: libfdb5.so needs its eckit/metkit siblings,
            # and a module-loaded toolchain may already be on the path.
            'export LD_LIBRARY_PATH="$FDB5_DIR/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"',
            "",
        ]

    lines += [
        "# pixi run activates the environment (PATH, CONDA_PREFIX, the activate.d",
        "# scripts that cartopy/pyproj need) before the kernel starts.",
        f'exec "{pixi}" run --manifest-path "{manifest}" '
        f'-e {args.environment} python -m ipykernel_launcher "$@"',
        "",
    ]
    return "\n".join(lines)


def main():
    args = parse_args()

    manifest = (Path(args.manifest_path).expanduser().resolve() if args.manifest_path
                else Path(__file__).resolve().parent.parent / "pixi.toml")
    if not manifest.exists():
        sys.exit(f"manifest not found: {manifest}")

    pixi = find_pixi(args.pixi)
    fdb5_dir = resolve_fdb5_dir(args)

    prefix = (Path(args.prefix).expanduser() if args.prefix else
              Path(os.environ.get("XDG_DATA_HOME", Path.home() / ".local" / "share"))
              / "jupyter")
    kernel_dir = prefix / "kernels" / args.name
    launcher = kernel_dir / "launch.sh"

    spec = {
        "argv": [str(launcher), "-f", "{connection_file}"],
        "display_name": args.display_name,
        "language": "python",
        "metadata": {"debugger": True},
    }
    launcher_text = render_launcher(args, pixi, manifest, fdb5_dir)

    if args.dry_run:
        print(f"# {launcher}")
        print(launcher_text)
        print(f"# {kernel_dir / 'kernel.json'}")
        print(json.dumps(spec, indent=2))
        return

    kernel_dir.mkdir(parents=True, exist_ok=True)
    launcher.write_text(launcher_text)
    launcher.chmod(launcher.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    (kernel_dir / "kernel.json").write_text(json.dumps(spec, indent=2) + "\n")

    print(f"wrote {kernel_dir}")
    print(f'  kernel   : "{args.display_name}"  (pixi env: {args.environment})')
    print(f"  manifest : {manifest}")
    if fdb5_dir:
        print(f"  FDB5_DIR : {fdb5_dir}")
    if args.modules:
        print(f"  modules  : {' '.join(args.modules)}")


if __name__ == "__main__":
    main()
